spring:
  data:
    mongodb:
      database: Bancos-DEV
      host: localhost
      port: 27017
      
controller:
  uri: /api/v1/bancos/coordenadas
  
headers:
  uuid: uuid
  countryCode: countryCode
  channelId: channelId
  businessCode: businessCode
