spring:
  data:
    mongodb:
      database: Bancos-SIT
      host: localhost
      port: 27017

controller:
  uri: /api/v1/bancos/estado/{state}
  
headers:
  accept: accept
  uuid: uuid
  countryCode: countryCode
  channelId: channelId
  businessCode: businessCode  
